These are some notes from the Daniel Bourke's "Learn PyTorch for deep learning in a day. Literally." YouTube course.
Link: https://www.youtube.com/watch?v=Z_ikDlimN6A

In [1]:
!pip install pandas
!pip install matplotlib
!pip install torch

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.8.1+cu102


In [3]:
# pytorch ternsor are usually created using the pytorch buildin function
# "torch.Tensor"
scalar = torch.tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as python int
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8], [8,9]])
MATRIX

tensor([[7, 8],
        [8, 9]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1,3,5],
                       [5,2,6],
                       [6,7,9]],
                       [[1,3,5],
                       [5,2,6],
                       [6,7,9]]])
TENSOR

tensor([[[1, 3, 5],
         [5, 2, 6],
         [6, 7, 9]],

        [[1, 3, 5],
         [5, 2, 6],
         [6, 7, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 3, 3])

In [15]:
# Random tensors
#create a random tensor of shape 3,4

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2251, 0.0520, 0.4198, 0.9626],
        [0.6625, 0.9449, 0.7348, 0.0224],
        [0.5091, 0.1622, 0.8119, 0.4414]])

In [16]:
random_tensor.shape

torch.Size([3, 4])

In [17]:
random_tensor.ndim

2

In [18]:
#create a random tensor with similar shape to an image tensor.
ran_image_size_tensor = torch.rand(size= (244, 244, 3)) #heigh, width, colour channels (r,g,b)
ran_image_size_tensor

tensor([[[0.1925, 0.4335, 0.0672],
         [0.4154, 0.4003, 0.4404],
         [0.8732, 0.1908, 0.0560],
         ...,
         [0.4910, 0.5246, 0.7876],
         [0.9963, 0.5591, 0.2294],
         [0.3516, 0.2170, 0.9601]],

        [[0.4772, 0.0126, 0.6339],
         [0.9892, 0.4084, 0.7332],
         [0.4730, 0.6231, 0.6061],
         ...,
         [0.8670, 0.1150, 0.9868],
         [0.0859, 0.9058, 0.0049],
         [0.4433, 0.3008, 0.8480]],

        [[0.8357, 0.3986, 0.4340],
         [0.4359, 0.4729, 0.8206],
         [0.3649, 0.5016, 0.4900],
         ...,
         [0.7926, 0.5232, 0.9523],
         [0.9782, 0.0657, 0.4206],
         [0.2674, 0.0526, 0.5654]],

        ...,

        [[0.9664, 0.4910, 0.9833],
         [0.5039, 0.2942, 0.2272],
         [0.4408, 0.9498, 0.8955],
         ...,
         [0.6025, 0.6208, 0.5209],
         [0.3356, 0.4601, 0.5073],
         [0.4899, 0.6263, 0.7963]],

        [[0.9050, 0.7128, 0.7718],
         [0.9213, 0.9056, 0.3137],
         [0.

In [19]:
ran_image_size_tensor.shape, ran_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [20]:
# Tensor of all zeros

zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Tensor of all ones

ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

# Creating a range of tensors and tensor-like

In [23]:
torch.__version__

'1.8.1+cu102'

In [24]:
# we can use torch.range...
torch.range(0,10)

/tmp/ipykernel_75/2132275013.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
# But if we are working on a futere version of torch like 1.10 >
# Then is probably better to use torch.arange.
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# torch.arange use a segmentation like this: (Start, stop, step)
torch.arange(2,15,2)
# We start the sequeence at 2 and take steps of 2 until we finish in 14.
# We put 15 instead of 14 because arange ends in n-1 like we show ahead.

tensor([ 2,  4,  6,  8, 10, 12, 14])

In [27]:
one_to_n = torch.arange(1,14)
one_to_n

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [28]:
# Creating Tensors like
# given a previous shape
one_to_n.shape

torch.Size([13])

In [29]:
#we can create a new tensor with the same shape or size but with, for example. zeros
zeros_like = torch.zeros_like(one_to_n)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
zeros_like.shape

torch.Size([13])

In [31]:
# float 32 tensor
float_32t = torch.tensor([3.0, 5.8, 3.9],
                        dtype = None, # What data type is the tensor (float32, float16...)
                        device = None, # What device is your tensor using (None, GPU)
                        requires_grad = False) # Whether or not to track gradients with this tensor operations.
float_32t

tensor([3.0000, 5.8000, 3.9000])

In [32]:
float_32t.dtype

torch.float32

In [33]:
float_16t = float_32t.type(torch.float16)
float_16t

tensor([3.0000, 5.8008, 3.9004], dtype=torch.float16)

In [34]:
float_16t.dtype

torch.float16

In [35]:
float_16t = float_32t.type(torch.half)
float_16t

tensor([3.0000, 5.8008, 3.9004], dtype=torch.float16)

In [36]:
float_16t.dtype

torch.float16

In [37]:
int_32t = torch.tensor([3,6,9],
                      dtype = torch.int32)
int_32t 

tensor([3, 6, 9], dtype=torch.int32)

# Getting information from tensors

In [38]:
# Datatype
int_32t.dtype

torch.int32

In [39]:
# Shape
int_32t.shape

torch.Size([3])

In [40]:
# Get the device
int_32t.device

device(type='cpu')

# Tensor manipulation

### Some tensor operations include:
* Addition
* Substraction
* Multiplication (element - wise)
* Division
* Matrix multiplication

In [41]:
Tensor1 = torch.rand(1,3,3)
Tensor1

tensor([[[0.6716, 0.0404, 0.7412],
         [0.1600, 0.8772, 0.2594],
         [0.4955, 0.2840, 0.6274]]])

In [42]:
Tensor2 = torch.rand(1,3,3)
Tensor2

tensor([[[0.8946, 0.0401, 0.6796],
         [0.6882, 0.4659, 0.6384],
         [0.3754, 0.3801, 0.3611]]])

In [43]:
Tensor1 + 10

tensor([[[10.6716, 10.0404, 10.7412],
         [10.1600, 10.8772, 10.2594],
         [10.4955, 10.2840, 10.6274]]])

In [44]:
# Using the torch buid in function to add
torch.add(Tensor1, 10)

tensor([[[10.6716, 10.0404, 10.7412],
         [10.1600, 10.8772, 10.2594],
         [10.4955, 10.2840, 10.6274]]])

In [45]:
Tensor1 - 10

tensor([[[-9.3284, -9.9596, -9.2588],
         [-9.8400, -9.1228, -9.7406],
         [-9.5045, -9.7160, -9.3726]]])

In [46]:
Tensor1 * 10

tensor([[[6.7164, 0.4037, 7.4120],
         [1.6000, 8.7723, 2.5936],
         [4.9548, 2.8396, 6.2742]]])

In [47]:
# Making multiplication with the torch build in function
torch.mul(Tensor1, 10)

tensor([[[6.7164, 0.4037, 7.4120],
         [1.6000, 8.7723, 2.5936],
         [4.9548, 2.8396, 6.2742]]])

In [48]:
# Matrix multiplication or dot product
torch.matmul(Tensor1, Tensor2)

tensor([[[0.9069, 0.3275, 0.7499],
         [0.8442, 0.5137, 0.7624],
         [0.8742, 0.3906, 0.7446]]])

### One of the rules of matrix multiplication is that the inner dimentrion must match as shown:
* (3,2) @ (3,2) won't work
* (3,2) @ (2,3) will work
* (2,3) @ (3,2) will work

In [49]:
op1 = torch.rand(3,2)
op2 = torch.rand(2,3)
op3 = torch.rand(2,3)

def try_mat_rule1(x, y):
    try:
        r = torch.matmul(x, y)
        print(f">> This operation is correct...")
        print(f"   {x.shape} @ {y.shape}")
        print(f"   returns: {r} {r.shape}")
    except:
        print(f">> is operation")
        print(f"   {x.shape} @ {y.shape} ")
        print(f"   !!!it  won't work")
        
try_mat_rule1(op1, op2)
try_mat_rule1(op3, op1)
try_mat_rule1(op2, op3)

>> This operation is correct...
   torch.Size([3, 2]) @ torch.Size([2, 3])
   returns: tensor([[0.3982, 0.2886, 0.4442],
        [0.4151, 0.4346, 0.6185],
        [0.9987, 0.9156, 1.3367]]) torch.Size([3, 3])
>> This operation is correct...
   torch.Size([2, 3]) @ torch.Size([3, 2])
   returns: tensor([[0.3414, 0.6077],
        [0.1152, 0.2295]]) torch.Size([2, 2])
>> is operation
   torch.Size([2, 3]) @ torch.Size([2, 3]) 
   !!!it  won't work


### Second rule...
The resulted matrix will have the shape of the outer dimensions

In [50]:
print(f"the **{op1.shape} @ {op2.shape} will result into **{torch.matmul(op1,op2).shape}")
print(f"the **{op3.shape} @ {op1.shape} will result into **{torch.matmul(op3,op1).shape}")

the **torch.Size([3, 2]) @ torch.Size([2, 3]) will result into **torch.Size([3, 3])
the **torch.Size([2, 3]) @ torch.Size([3, 2]) will result into **torch.Size([2, 2])


### Adjusting the shape of tensors

In [51]:
# We can manipulate the shape of the tensor using the method transpose

print(f"Initializing with a tensor like:")
print(f"{op1} habvin a shape {op1.shape}")

op1T = op1.T

print(f"We use the transpose funtion to altere the shape like this:")
print(f"{op1T}, shape: {op1T.shape}")

Initializing with a tensor like:
tensor([[0.0432, 0.4165],
        [0.2828, 0.3745],
        [0.4490, 0.9591]]) habvin a shape torch.Size([3, 2])
We use the transpose funtion to altere the shape like this:
tensor([[0.0432, 0.2828, 0.4490],
        [0.4165, 0.3745, 0.9591]]), shape: torch.Size([2, 3])


### Tensor aggregation...
min, max, mean, sum, etc

In [52]:
Tensor3 = torch.arange(0, 100 ,10)
Tensor3

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
# Finding min, max
torch.min(Tensor3), torch.max(Tensor3), Tensor3.min(), Tensor3.max()

(tensor(0), tensor(90), tensor(0), tensor(90))

In [54]:
# Finding the mean
# The above code launch an error because of the dtype.
# We manage to solve this error by converting the original dtype from in 64 to float32 using the "type" function.
torch.mean(Tensor3.type(torch.float32)), Tensor3.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [55]:
# Findinf sum
torch.sum(Tensor3), Tensor3.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [56]:
Tensor3.argmin(), Tensor3.argmax()

(tensor(0), tensor(9))

### Reshaping, Stacking, squeezing and un squeezing

* Reshaping - Reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Conbine multiple tensors on top of each other (V-stack) or side by side (H-stack)

* Squeeze - Removes all '1' dimension from a tensor
* Unsqueeze - Add a '1' dimension to a target tensor
* Permute - Return a view of the input with the dimensions permuted (swaped) in a certain way

**Reshape**

In [57]:
# Given a original vector
Tensor3, Tensor3.shape

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.Size([10]))

In [58]:
# we can reshape the given tensro above for other shape that match the number size that it already has like so:
print(f">> Original:\n {Tensor3.shape , Tensor3}\n")
print(f">> Shape 1:\n {Tensor3.reshape(1,10).shape , Tensor3.reshape(1,10)}\n")
print(f">> Shape 2:\n {Tensor3.reshape(2,5).shape, Tensor3.reshape(2,5)}\n")
print(f">> shape 3:\n {Tensor3.reshape(5,2).shape, Tensor3.reshape(5,2)}\n")
print(f">> shape 3:\n {Tensor3.reshape(10,1).shape, Tensor3.reshape(10,1)}")

>> Original:
 (torch.Size([10]), tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

>> Shape 1:
 (torch.Size([1, 10]), tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]))

>> Shape 2:
 (torch.Size([2, 5]), tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]]))

>> shape 3:
 (torch.Size([5, 2]), tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]]))

>> shape 3:
 (torch.Size([10, 1]), tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]]))


**View**

In [59]:
# changing view...
x = torch.arange(1, 15)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
# The function view share the same sapace memory with the original tensor
z = x.view(2,7)
print(f"z = {z}\nx = {x}")

z = tensor([[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]])
x = tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


In [61]:
# Thus, if we change a tensor made with the view function, this will change the original and vice versa
# Here we changed the first number of the first dimension of the z tensor to 6...
# and now we see how the first number of the x tensor change to 6 too but everything else stays the equal
z[0][0]= 6
print(f"z = {z}\nx = {x}")

z = tensor([[ 6,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]])
x = tensor([ 6,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


**Stacking**

In [62]:
# Stack tensors on top of each other depending on the number of dimensions
# The dimension number must be compatuble with the original tensor.
stacked1 = torch.stack([x,x,x,x], dim= 0) # 0 is the dim by default
stacked2 = torch.stack([x,x,x,x], dim= 1)
stacked3 = torch.stack([x,x,x,x], dim= -2)

stacked1, stacked2, stacked2

(tensor([[ 6,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
         [ 6,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
         [ 6,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
         [ 6,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 tensor([[ 6,  6,  6,  6],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3],
         [ 4,  4,  4,  4],
         [ 5,  5,  5,  5],
         [ 6,  6,  6,  6],
         [ 7,  7,  7,  7],
         [ 8,  8,  8,  8],
         [ 9,  9,  9,  9],
         [10, 10, 10, 10],
         [11, 11, 11, 11],
         [12, 12, 12, 12],
         [13, 13, 13, 13],
         [14, 14, 14, 14]]),
 tensor([[ 6,  6,  6,  6],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3],
         [ 4,  4,  4,  4],
         [ 5,  5,  5,  5],
         [ 6,  6,  6,  6],
         [ 7,  7,  7,  7],
         [ 8,  8,  8,  8],
         [ 9,  9,  9,  9],
         [10, 10, 10, 10],
         [11, 11, 11, 11],
         [12, 12, 12, 12],
         [13, 13, 13, 13],

### Squeezing, unsqueezing and permuting

**Squeeze**

In [63]:
# squeeze = tensor.squeeze
forsuqeeze1 = torch.rand(1,1,14)
forsuqeeze2 = torch.rand(1,2,14)
print(f">> For a shape like squeeze 1\n\n>>>{forsuqeeze1.shape}\n\n  {forsuqeeze1}\n\n>>>{forsuqeeze1.squeeze().shape}\n\n   {forsuqeeze1.squeeze()}\n\n")
print(f">> for a shape like squeeze 2\n\n>>>{forsuqeeze2.shape}\n\n  {forsuqeeze2}\n\n>>>{forsuqeeze2.squeeze().shape}\n\n   {forsuqeeze2.squeeze()}\n\n")

>> For a shape like squeeze 1

>>>torch.Size([1, 1, 14])

  tensor([[[0.8709, 0.8169, 0.7628, 0.5075, 0.5160, 0.1089, 0.7252, 0.8997,
          0.0814, 0.8737, 0.4666, 0.7984, 0.3785, 0.4659]]])

>>>torch.Size([14])

   tensor([0.8709, 0.8169, 0.7628, 0.5075, 0.5160, 0.1089, 0.7252, 0.8997, 0.0814,
        0.8737, 0.4666, 0.7984, 0.3785, 0.4659])


>> for a shape like squeeze 2

>>>torch.Size([1, 2, 14])

  tensor([[[0.0875, 0.3282, 0.3598, 0.2993, 0.1835, 0.9528, 0.3887, 0.2110,
          0.4972, 0.0756, 0.3862, 0.7653, 0.8464, 0.8506],
         [0.4223, 0.7153, 0.2635, 0.4358, 0.8811, 0.9066, 0.3045, 0.1476,
          0.3709, 0.1692, 0.6263, 0.6256, 0.0383, 0.2908]]])

>>>torch.Size([2, 14])

   tensor([[0.0875, 0.3282, 0.3598, 0.2993, 0.1835, 0.9528, 0.3887, 0.2110, 0.4972,
         0.0756, 0.3862, 0.7653, 0.8464, 0.8506],
        [0.4223, 0.7153, 0.2635, 0.4358, 0.8811, 0.9066, 0.3045, 0.1476, 0.3709,
         0.1692, 0.6263, 0.6256, 0.0383, 0.2908]])




**Unsqueeze**

In [64]:
# unsqueeze = tensor.unsqueeze
print(f">> For a shape like squeeze 1\n\n>>>{forsuqeeze1.shape}\n\n  {forsuqeeze1.unsqueeze(dim=1)}\n\n")
print(f">> for a shape like squeeze 2\n\n>>>{forsuqeeze2.shape}\n\n  {forsuqeeze2}\n\n dim=1 pos=[1]... \n>>>{forsuqeeze2.unsqueeze(dim=1).shape}\n\n dim=2 pos=[2]... \n>>>{forsuqeeze2.unsqueeze(dim=2).shape}\n\n dim=3 pos=[3]... \n>>>{forsuqeeze2.unsqueeze(dim=3).shape}\n\n   {forsuqeeze2.unsqueeze(dim=3)}\n\n")

>> For a shape like squeeze 1

>>>torch.Size([1, 1, 14])

  tensor([[[[0.8709, 0.8169, 0.7628, 0.5075, 0.5160, 0.1089, 0.7252, 0.8997,
           0.0814, 0.8737, 0.4666, 0.7984, 0.3785, 0.4659]]]])


>> for a shape like squeeze 2

>>>torch.Size([1, 2, 14])

  tensor([[[0.0875, 0.3282, 0.3598, 0.2993, 0.1835, 0.9528, 0.3887, 0.2110,
          0.4972, 0.0756, 0.3862, 0.7653, 0.8464, 0.8506],
         [0.4223, 0.7153, 0.2635, 0.4358, 0.8811, 0.9066, 0.3045, 0.1476,
          0.3709, 0.1692, 0.6263, 0.6256, 0.0383, 0.2908]]])

 dim=1 pos=[1]... 
>>>torch.Size([1, 1, 2, 14])

 dim=2 pos=[2]... 
>>>torch.Size([1, 2, 1, 14])

 dim=3 pos=[3]... 
>>>torch.Size([1, 2, 14, 1])

   tensor([[[[0.0875],
          [0.3282],
          [0.3598],
          [0.2993],
          [0.1835],
          [0.9528],
          [0.3887],
          [0.2110],
          [0.4972],
          [0.0756],
          [0.3862],
          [0.7653],
          [0.8464],
          [0.8506]],

         [[0.4223],
          [0.7153],

**Permute**\
Rearange the target dimensions on a specified order

In [65]:
# torch.permute()
# The permute function share the same space in memory so if we what ever tensor assosiated with the permute Function
# it will be change on all the tensors associated
x1 = torch.rand(255, 255, 3) # [height, width, colour_channels] -> (a commond representation of image data)

# Permute x1 to rearange in the order [colour_channels, height, width]
x1_perm= x1.permute(2, 0, 1)
print(f"\nOriginal =\n   >> {x1.shape}\n\nPermuted =\n   >> {x1_perm.shape}")



Original =
   >> torch.Size([255, 255, 3])

Permuted =
   >> torch.Size([3, 255, 255])


### Indexing

In [66]:
# Given an original tensor...
x2= torch.arange(3,28,3).reshape(1,3,3)
x2 , x2.shape

(tensor([[[ 3,  6,  9],
          [12, 15, 18],
          [21, 24, 27]]]),
 torch.Size([1, 3, 3]))

In [67]:
# Now we index the tensor
print(f"Original: \n>>> {x2}\n\n")
print(f"First index x2[0]: \n>>> {x2[0]}\n\n")
print(f"First index and second index inside of it x2[0][1]>>> \n>>> {x2[0][1]}\n\n")
print(f"->[Alternative] Same as the last one but with a different method x2[0,1]: \n  >>> {x2[0,1]}\n\n")
print(f"Third number inside the second line of the first index x2[0][1][2]: \n>>> {x2[0][1][2]}\n\n")
print(f"->[Alternative] Same as the last one but with a different method x2[0,1,2]: \n  >>> {x2[0,1,2]}\n\n")

Original: 
>>> tensor([[[ 3,  6,  9],
         [12, 15, 18],
         [21, 24, 27]]])


First index x2[0]: 
>>> tensor([[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]])


First index and second index inside of it x2[0][1]>>> 
>>> tensor([12, 15, 18])


->[Alternative] Same as the last one but with a different method x2[0,1]: 
  >>> tensor([12, 15, 18])


Third number inside the second line of the first index x2[0][1][2]: 
>>> 18


->[Alternative] Same as the last one but with a different method x2[0,1,2]: 
  >>> 18




In [68]:
# We can algo use the ':' to select all items from a target dimension
x2[:,1]

tensor([[12, 15, 18]])

In [69]:
# Getting all elements of the and second dimension but only the second element of the third dimension
# Graphic explaination >>> totch.size([n, n, n]) we mark with "Xpos" our target >>> torch.size([:, :, X2])
# Now in matrix format >>> tensor([[ n, X, n],
#                                  [ n, X, n],
#                                  [ n, X, n]])
x2, x2[:,:,1]

(tensor([[[ 3,  6,  9],
          [12, 15, 18],
          [21, 24, 27]]]),
 tensor([[ 6, 15, 24]]))

In [70]:
# A little diffenrence to having in mind about the indexing with ':'
# If we put the ':' at the beguinig, it returns us the first dimention of the tensor with the desired one
# If we dont put the ':' but the dimension itself, it returns us only the desired dimension
x2, x2[:,1,1], x2[0,1,1]

(tensor([[[ 3,  6,  9],
          [12, 15, 18],
          [21, 24, 27]]]),
 tensor([15]),
 tensor(15))

In [71]:
# If we put the ':' at last it returns only all the elements of the last dimension
x2, x2[0,2,:], x2[0,2]

(tensor([[[ 3,  6,  9],
          [12, 15, 18],
          [21, 24, 27]]]),
 tensor([21, 24, 27]),
 tensor([21, 24, 27]))

# Pytorch tensors and NumPy
Due that Pytorch have dependencies and integration with NumPy we will possibly need to use this Python library in somo of our work. That is why we'll have in mind that the data in NumPy has it's own type, "ndaarray", and we will probbably need to convert it to a Tensor type to process it with torch.
we can use "**torch.from_numpy(ndarray)**" to pass it from NumPy type to tensor and "**torch.tensor.numpy()**" from tensor to NumPy

In [82]:
# Numpy to Tensor
narray = np.arange(2.0, 42.0, 3.0)
ntensor = torch.from_numpy(narray)
print(f"Type narray=\n{type(narray)}\n {narray}\n\nType ntensor=\n{type(ntensor)}\n {ntensor}")

Type narray=
<class 'numpy.ndarray'>
 [ 2.  5.  8. 11. 14. 17. 20. 23. 26. 29. 32. 35. 38. 41.]

Type ntensor=
<class 'torch.Tensor'>
 tensor([ 2.,  5.,  8., 11., 14., 17., 20., 23., 26., 29., 32., 35., 38., 41.],
       dtype=torch.float64)


In [87]:
# We need to have in mind that both, NumPy and Pytorch, create a different dtype by default
# Numpy create a float-64 and Pytorch a float-32 as shown afete:
print(f"NumPy dtype = \n {np.arange(0.0,10.0).dtype}\n\nPytorch dtype = \n {torch.arange(0.0,10.0).dtype}")

NumPy dtype = 
 float64

Pytorch dtype = 
 torch.float32


In [89]:
# From tensor to NumPy
ntensor = torch.arange(20.0,30.0)
narray = ntensor.numpy()
print(f"Type ntensor=\n{type(ntensor)}\n {ntensor}\n\nType narray=\n{type(narray)}\n {narray}")

Type ntensor=
<class 'torch.Tensor'>
 tensor([20., 21., 22., 23., 24., 25., 26., 27., 28., 29.])

Type narray=
<class 'numpy.ndarray'>
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]


## Reproducibility (Trying to take random out of random)
We use a random seed to reduce a bit the randomness of our values or experiments

In [112]:
# Everytime we run this cell, we will find that the output is different
torch.rand(3,3), torch.rand(3,3), torch.rand(3,3)

(tensor([[0.1182, 0.4387, 0.8180],
         [0.0982, 0.0503, 0.7128],
         [0.8284, 0.1884, 0.1025]]),
 tensor([[0.8272, 0.3180, 0.4504],
         [0.1100, 0.3681, 0.0187],
         [0.9573, 0.3108, 0.5141]]),
 tensor([[0.7260, 0.5707, 0.3254],
         [0.2919, 0.8707, 0.3518],
         [0.8129, 0.2901, 0.6826]]))

In [119]:
# Now we use a random seed to minimize a little that randomness of the begining so we can work with
# a little bit more predictable numbers, that allow us to reproduce somehow the results we are achieving
# here in other processes
# First we use a number as random seed, generaly 42 or somewher arond
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
torch.rand(3,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [121]:
# Now we see that our seed is replicating the results we get before, making the beheabore of our randomness
# so much more predictable thus we can get similar results and iterate more easily the process
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
torch.rand(3,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [122]:
# We need to have in mind that the RANDOM_SEED just works for one line of code 
torch.rand(3,3)

tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

In [125]:
# so if we want to use it again we will need to call it again
torch.manual_seed(RANDOM_SEED)
torch.rand(3,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])